name: hero_dex
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/mask.png
    - assets/images/loki.png
    - assets/images/deadpool.png
    - assets/images/all.png
    - assets/superhero.json

  fonts:
    - family: JMH Typewriter
      fonts:
        - asset: assets/fonts/JMH Typewriter-Thin.ttf
        - asset: assets/fonts/JMH Typewriter-Bold.ttf
        - asset: assets/fonts/JMH Typewriter-Black.ttf
        - asset: assets/fonts/JMH Typewriter.ttf
        
